
### Obtener a Ditto
GET http://localhost:1234/pokemon/ditto


### Crear un nuevo Pokémon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "Pikachu",
  "type": "Electric",
  "moves": [
    "Thunderbolt",
    "Quick Attack"
  ]
}

